-- TODO create SQL Schema Script
-- DATABASE Selected


use goforit;

DROP TABLE TRUST;

DROP TABLE COMMENT;

DROP TABLE POST;

DROP TABLE PLACE_MEMBERSHIP;

DROP TABLE PLACE;

DROP TABLE USER_FRIEND;

DROP TABLE USER;

CREATE TABLE USER (USER_ID BIGINT PRIMARY KEY, FIRST_NAME VARCHAR(45), 
LAST_NAME VARCHAR(45), PASSWORD VARCHAR(45), EMAIL_ADDRESS VARCHAR(45), 
PHONE_NUMBER BIGINT, CREATED_ON TIMESTAMP, PENDING_POSTS INT, 
PENDING_COMMENTS INT, TRUST_FACTOR BIGINT, UNIQUE KEY (EMAIL_ADDRESS));

CREATE TABLE USER_FRIEND (USER_ID BIGINT, FRIEND_ID BIGINT, FRIEND_TYPE VARCHAR(10), 
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID), FOREIGN KEY(FRIEND_ID) REFERENCES USER(USER_ID));

CREATE TABLE PLACE (PLACE_ID BIGINT PRIMARY KEY, PLACE_NAME VARCHAR(45), PLACE_ADDRESS VARCHAR(255), 
CREATED_BY BIGINT, CREATED_ON TIMESTAMP, TOPIC_NAME VARCHAR(20), 
FOREIGN KEY (CREATED_BY) REFERENCES USER(USER_ID));

CREATE TABLE POST (POST_ID BIGINT PRIMARY KEY, PLACE_POSTED BIGINT, POSTED_BY BIGINT, 
POSTED_ON TIMESTAMP, POST_CONTENT VARCHAR(255), CONTENT_TYPE VARCHAR(10), 
FOREIGN KEY(PLACE_POSTED) REFERENCES PLACE(PLACE_ID), FOREIGN KEY(POSTED_BY) REFERENCES USER(USER_ID));

CREATE TABLE COMMENT (COMMENT_ID BIGINT PRIMARY KEY, PARENT_POST_ID BIGINT, COMMENTED_BY BIGINT, 
COMMENTED_ON TIMESTAMP, COMMENT_CONTENT VARCHAR(255), CONTENT_TYPE VARCHAR(10), 
FOREIGN KEY(PARENT_POST_ID) REFERENCES POST(POST_ID), FOREIGN KEY(COMMENTED_BY) REFERENCES USER(USER_ID));

CREATE TABLE TRUST_POST (TRUST_ID BIGINT PRIMARY KEY, TRUSTED_BY BIGINT, TRUSTED_POST BIGINT, 
TRUSTED_USER BIGINT, TRUSTED_ON TIMESTAMP, FOREIGN KEY(TRUSTED_BY) REFERENCES USER(USER_ID), 
FOREIGN KEY(TRUSTED_POST) REFERENCES POST(POST_ID), FOREIGN KEY(TRUSTED_USER) REFERENCES USER(USER_ID));

CREATE TABLE TRUST_PLACE (TRUST_ID BIGINT PRIMARY KEY, TRUSTED_BY BIGINT, TRUSTED_PLACE BIGINT, 
TRUSTED_USER BIGINT, TRUSTED_ON TIMESTAMP, FOREIGN KEY(TRUSTED_BY) REFERENCES USER(USER_ID), 
FOREIGN KEY(TRUSTED_PLACE) REFERENCES PLACE(PLACE_ID), FOREIGN KEY(TRUSTED_USER) REFERENCES USER(USER_ID));

CREATE TABLE PLACE_MEMBERSHIP (MEMBERSHIP_ID BIGINT PRIMARY KEY, PLACE_ID BIGINT, 
MEMBER_ID BIGINT, MEMBERSHIP_TYPE VARCHAR(10), 
FOREIGN KEY(PLACE_ID) REFERENCES PLACE(PLACE_ID), FOREIGN KEY(MEMBER_ID) REFERENCES USER(USER_ID));

COMMIT;
